# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/supersearch.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/supersearch.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/supersearch.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/supersearch.dir/flags.make

CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o: ../rapidJSONExample.cpp
CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o -MF CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o.d -o CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/rapidJSONExample.cpp

CMakeFiles/supersearch.dir/rapidJSONExample.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/rapidJSONExample.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/rapidJSONExample.cpp > CMakeFiles/supersearch.dir/rapidJSONExample.cpp.i

CMakeFiles/supersearch.dir/rapidJSONExample.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/rapidJSONExample.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/rapidJSONExample.cpp -o CMakeFiles/supersearch.dir/rapidJSONExample.cpp.s

CMakeFiles/supersearch.dir/IndexHandler.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/IndexHandler.cpp.o: ../IndexHandler.cpp
CMakeFiles/supersearch.dir/IndexHandler.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/supersearch.dir/IndexHandler.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/IndexHandler.cpp.o -MF CMakeFiles/supersearch.dir/IndexHandler.cpp.o.d -o CMakeFiles/supersearch.dir/IndexHandler.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/IndexHandler.cpp

CMakeFiles/supersearch.dir/IndexHandler.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/IndexHandler.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/IndexHandler.cpp > CMakeFiles/supersearch.dir/IndexHandler.cpp.i

CMakeFiles/supersearch.dir/IndexHandler.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/IndexHandler.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/IndexHandler.cpp -o CMakeFiles/supersearch.dir/IndexHandler.cpp.s

CMakeFiles/supersearch.dir/DocumentParser.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/DocumentParser.cpp.o: ../DocumentParser.cpp
CMakeFiles/supersearch.dir/DocumentParser.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/supersearch.dir/DocumentParser.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/DocumentParser.cpp.o -MF CMakeFiles/supersearch.dir/DocumentParser.cpp.o.d -o CMakeFiles/supersearch.dir/DocumentParser.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/DocumentParser.cpp

CMakeFiles/supersearch.dir/DocumentParser.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/DocumentParser.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/DocumentParser.cpp > CMakeFiles/supersearch.dir/DocumentParser.cpp.i

CMakeFiles/supersearch.dir/DocumentParser.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/DocumentParser.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/DocumentParser.cpp -o CMakeFiles/supersearch.dir/DocumentParser.cpp.s

CMakeFiles/supersearch.dir/Word.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/Word.cpp.o: ../Word.cpp
CMakeFiles/supersearch.dir/Word.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/supersearch.dir/Word.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/Word.cpp.o -MF CMakeFiles/supersearch.dir/Word.cpp.o.d -o CMakeFiles/supersearch.dir/Word.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/Word.cpp

CMakeFiles/supersearch.dir/Word.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/Word.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/Word.cpp > CMakeFiles/supersearch.dir/Word.cpp.i

CMakeFiles/supersearch.dir/Word.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/Word.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/Word.cpp -o CMakeFiles/supersearch.dir/Word.cpp.s

CMakeFiles/supersearch.dir/documentID.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/documentID.cpp.o: ../documentID.cpp
CMakeFiles/supersearch.dir/documentID.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/supersearch.dir/documentID.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/documentID.cpp.o -MF CMakeFiles/supersearch.dir/documentID.cpp.o.d -o CMakeFiles/supersearch.dir/documentID.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/documentID.cpp

CMakeFiles/supersearch.dir/documentID.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/documentID.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/documentID.cpp > CMakeFiles/supersearch.dir/documentID.cpp.i

CMakeFiles/supersearch.dir/documentID.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/documentID.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/documentID.cpp -o CMakeFiles/supersearch.dir/documentID.cpp.s

CMakeFiles/supersearch.dir/UserInterface.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/UserInterface.cpp.o: ../UserInterface.cpp
CMakeFiles/supersearch.dir/UserInterface.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/supersearch.dir/UserInterface.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/UserInterface.cpp.o -MF CMakeFiles/supersearch.dir/UserInterface.cpp.o.d -o CMakeFiles/supersearch.dir/UserInterface.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/UserInterface.cpp

CMakeFiles/supersearch.dir/UserInterface.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/UserInterface.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/UserInterface.cpp > CMakeFiles/supersearch.dir/UserInterface.cpp.i

CMakeFiles/supersearch.dir/UserInterface.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/UserInterface.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/UserInterface.cpp -o CMakeFiles/supersearch.dir/UserInterface.cpp.s

CMakeFiles/supersearch.dir/AVLMap.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/AVLMap.cpp.o: ../AVLMap.cpp
CMakeFiles/supersearch.dir/AVLMap.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/supersearch.dir/AVLMap.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/AVLMap.cpp.o -MF CMakeFiles/supersearch.dir/AVLMap.cpp.o.d -o CMakeFiles/supersearch.dir/AVLMap.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/AVLMap.cpp

CMakeFiles/supersearch.dir/AVLMap.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/AVLMap.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/AVLMap.cpp > CMakeFiles/supersearch.dir/AVLMap.cpp.i

CMakeFiles/supersearch.dir/AVLMap.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/AVLMap.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/AVLMap.cpp -o CMakeFiles/supersearch.dir/AVLMap.cpp.s

CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o: CMakeFiles/supersearch.dir/flags.make
CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o: ../porter2_stemmer-master/porter2_stemmer.cpp
CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o: CMakeFiles/supersearch.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o -MF CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o.d -o CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o -c /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/porter2_stemmer-master/porter2_stemmer.cpp

CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/porter2_stemmer-master/porter2_stemmer.cpp > CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.i

CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/porter2_stemmer-master/porter2_stemmer.cpp -o CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.s

# Object files for target supersearch
supersearch_OBJECTS = \
"CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o" \
"CMakeFiles/supersearch.dir/IndexHandler.cpp.o" \
"CMakeFiles/supersearch.dir/DocumentParser.cpp.o" \
"CMakeFiles/supersearch.dir/Word.cpp.o" \
"CMakeFiles/supersearch.dir/documentID.cpp.o" \
"CMakeFiles/supersearch.dir/UserInterface.cpp.o" \
"CMakeFiles/supersearch.dir/AVLMap.cpp.o" \
"CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o"

# External object files for target supersearch
supersearch_EXTERNAL_OBJECTS =

supersearch: CMakeFiles/supersearch.dir/rapidJSONExample.cpp.o
supersearch: CMakeFiles/supersearch.dir/IndexHandler.cpp.o
supersearch: CMakeFiles/supersearch.dir/DocumentParser.cpp.o
supersearch: CMakeFiles/supersearch.dir/Word.cpp.o
supersearch: CMakeFiles/supersearch.dir/documentID.cpp.o
supersearch: CMakeFiles/supersearch.dir/UserInterface.cpp.o
supersearch: CMakeFiles/supersearch.dir/AVLMap.cpp.o
supersearch: CMakeFiles/supersearch.dir/porter2_stemmer-master/porter2_stemmer.cpp.o
supersearch: CMakeFiles/supersearch.dir/build.make
supersearch: CMakeFiles/supersearch.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Linking CXX executable supersearch"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/supersearch.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/supersearch.dir/build: supersearch
.PHONY : CMakeFiles/supersearch.dir/build

CMakeFiles/supersearch.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/supersearch.dir/cmake_clean.cmake
.PHONY : CMakeFiles/supersearch.dir/clean

CMakeFiles/supersearch.dir/depend:
	cd /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug /Users/devoncoates/Documents/GitHub/assignment-4-search-engine-ryan-devon/cmake-build-debug/CMakeFiles/supersearch.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/supersearch.dir/depend

